// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejnyjkcvdstdvyfrquwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbnlqa2N2ZHN0ZHZ5ZnJxdXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTUwMzUsImV4cCI6MjA1OTA5MTAzNX0.8gDA2bca4no4LQk0tTNWvWzfZwf33Q9xPYZoC4EGqZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);